#!/bin/bash

cd ..
rm -rf livemix-$1
cp -a livemix livemix-$1
cd livemix-$1

make clean
make distclean

rm -rf .settings
rm config.h build-stamp config.guess config.sub .cdtproject .project i18n/livemix_fr.qm
find . -name .svn -print | while read f;
do
   rm -rf $f
done
find . -name objs -print | while read f;
do
   rm -rf $f
done
find . -name libs -print | while read f;
do
   rm -rf $f
done
find . -name "*~" -print | while read f;
do
   rm $f
done

?      data/fader_background_1.svg
?      data/fader_leds1.svg
?      data/intro-close_1.svg
?      data/intro-open_1.svg
?      data/fader_top_1.svg
?      data/fader_leds_1.svg
?      i18n/livemix_fr.qm


echo "----"
