#!/bin/bash

prefix=../livemix-$1-bin ./configure
touch livemix
chmod +x livemix
make qmake
rm livemix
make
rm -rf livemix-$1-bin
make install
cd ..
tar -cvjf livemix-$1-bin.tar.bz2 livemix-$1-bin
cd livemix

