#!/bin/bash

echo "build livemix-$1 ($2 $3)"

./copysrc $1

cd ..

rm livemix_$1*

tar --exclude=debian -cvhzf livemix_$1.orig.tar.gz livemix-$1

cd livemix-$1

dpkg-buildpackage $2 $3 -rfakeroot
#-S -sa

cd ../livemix

lintian ../livemix_$1*.dsc
linda ../livemix_$1*.dsc

echo "For pbuilder"
echo "sudo pbuilder create --distribution gusty --othermirror \"deb http://archive.ubuntu.com/ubuntu gutsy main universe multiverse\""
echo "sudo pbuilder update --distribution gusty"
echo "cp ../livemix_$1* /home/public"
echo "sudo pbuilder build --distribution gusty /home/public/livemix_$1-0ubuntu1.dsc"
echo "----"
echo "To upload use: dput ../livemix_$1-1.0_source.changes"