#!/bin/bash

echo "build livemix-$1"

./copysrc $1

cd ..

rm livemix_$1*

tar --exclude=debian -cvhzf livemix_$1.orig.tar.gz livemix-$1

cd livemix-$1

dpkg-buildpackage -rfakeroot

cd ../livemix

rm -rf ../livemix-$1

lintian ../livemix_$1*.dsc
linda ../livemix_$1*.dsc
