#!/bin/bash

sudo ls>/dev/null

./mksrc $1
cp ../livemix-$1.tar.bz2 ../OK

cd ../livemix-$1

./mkbin $1
cp ../livemix-$1-bin.tar.bz2 ../OK

./mkdeb $1
sudo dpkg -i ../livemix_$1-0ubuntu1_i386.deb
cp ../livemix_$1-0ubuntu1_i386.deb ../OK
gzip -c ../OK/livemix_$1-0ubuntu1_i386.deb > ../OK/livemix_$1-0ubuntu1_i386.deb.gz

./mkdebsrc $1

echo "svn commit -m \"Commiting the $1 release of the 'livemix' project.\""
echo "svn copy http://svn.codingteam.net/code/livemix/trunk http://svn.codingteam.net/code/livemix/tags/$1 -m \"Tagging the $1 release of the 'livemix' project.\""