#!/bin/bash

cd ..
cp -a livemix livemix-$1
cd livemix-$1
make clean
make dist-clean
find . -name .svn -print | while read f;
do
   rm -rf $f
done
find . -name objs -print | while read f;
do
   rm -rf $f
done
find . -name libs -print | while read f;
do
   rm -rf $f
done
find . -name *~ -print | while read f;
do
   rm $f
done
find . -name Makefile -print | while read f;
do
   rm $f
done
find . -name Makefile.am -print | while read f;
do
   rm $f
done
cd ..
tar -cvjf livemix-$1.tar.bz2 livemix-$1
rm -rf livemix-$1
cd livemix
